import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import ts from 'typescript';

async function moduleOf(file, adapt = source => source) {
  const source = adapt(await readFile(new URL(file, import.meta.url), 'utf8'));
  const compiled = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext } }).outputText;
  return import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);
}
const { createLoadingClock } = await moduleOf('../lib/loading-clock.ts');
let stamp = 0;
const listeners = new Set();
globalThis.performance = { now: () => stamp };
globalThis.document = { hidden: false, addEventListener: (_name, fn) => listeners.add(fn), removeEventListener: (_name, fn) => listeners.delete(fn) };
const visibility = hidden => { document.hidden = hidden; for (const fn of listeners) fn(); };
const clock = createLoadingClock();
stamp = 900;
assert.equal(clock.now(), 900);
visibility(true);
stamp = 61000;
assert.equal(clock.now(), 900, 'a suspended work does not use its rendering budget');
visibility(false);
stamp = 61500;
assert.equal(clock.now(), 1400, 'resume retains the remaining foreground budget');
visibility(true);
stamp = 90000;
visibility(false);
stamp += 100;
assert.equal(clock.now(), 1500);
clock.dispose();
assert.equal(listeners.size, 0);
visibility(true);
const hiddenClock = createLoadingClock();
stamp += 30000;
assert.equal(hiddenClock.now(), 0, 'a deep link created in a background tab gets its full budget');
hiddenClock.dispose();
console.log('PASS loading clock: visible time, hide/resume, repeated switches, hidden mount, cleanup');

const { apiReadJson } = await moduleOf('../lib/api.ts', source => source.replace('import.meta.env.VITE_API_BASE_URL', 'undefined'));
let id = 0;
const timers = new Map();
globalThis.setTimeout = (fn, ms) => { assert.equal(ms, 12000); timers.set(++id, fn); return id; };
globalThis.clearTimeout = token => timers.delete(token);
const expire = () => { for (const fn of timers.values()) fn(); };
const aborted = signal => new Promise((_resolve, reject) => {
  const fail = () => reject(new DOMException('Aborted', 'AbortError'));
  if (signal.aborted) fail(); else signal.addEventListener('abort', fail, { once: true });
});
globalThis.fetch = async (_url, options) => { assert.equal(options.credentials, 'include'); return { ok: true, json: async () => ({ works: [] }) }; };
assert.deepEqual(await apiReadJson('/api/works'), { works: [] });
assert.equal(timers.size, 0);
globalThis.fetch = async () => ({ ok: false });
assert.equal(await apiReadJson('/api/works'), null);
assert.equal(timers.size, 0);
globalThis.fetch = async (_url, { signal }) => aborted(signal);
const hanging = apiReadJson('/api/works');
expire();
await assert.rejects(hanging, { name: 'AbortError' });
assert.equal(timers.size, 0);
globalThis.fetch = async (_url, { signal }) => ({ ok: true, json: () => aborted(signal) });
const body = apiReadJson('/api/prompts');
await Promise.resolve();
expire();
await assert.rejects(body, { name: 'AbortError' });
assert.equal(timers.size, 0);
const controller = new AbortController();
const cancelled = apiReadJson('/api/works', controller.signal);
controller.abort();
await assert.rejects(cancelled, { name: 'AbortError' });
await assert.rejects(apiReadJson('/api/works', controller.signal), { name: 'AbortError' });
assert.equal(timers.size, 0);
console.log('PASS read deadline: normal/HTTP failure, hanging headers/body, caller abort, pre-abort, timer cleanup');
