import assert from 'node:assert/strict';
import { fixture, loadMotion } from './motion-fixture.mjs';
const { SurfaceTransition } = await loadMotion('lib/ui-transitions.ts');
const f = fixture(), root = f.element(), panel = f.element();
const transition = new SurfaceTransition(root, panel, 300, 200);
transition.show(false);
assert.equal(root.hidden, false);
assert.equal(root.dataset.transition, 'opening');
await f.advance(300);
assert.equal(root.dataset.transition, 'open');
assert.ok(f.all.every(a => a.frames.every(frame => !('opacity' in frame) && !('transform' in frame))), 'text containers must not composite on entry');
assert.equal(f.active.size, 0);
let closed = 0;
transition.hide(false, () => closed++);
await f.advance(200);
assert.equal(root.hidden, true);
assert.equal(closed, 1);
transition.show(false);
await f.advance(100);
const halfway = getComputedStyle(root).backgroundColor;
transition.hide(false, () => closed++);
assert.equal(f.all.at(-2).frames[0].backgroundColor, halfway, 'interruption resumes the visible surface color');
await f.advance(200);
assert.equal(root.dataset.transition, 'closed');
assert.equal(closed, 2);
transition.hide(false, () => closed++);
assert.equal(closed, 3);
transition.show(true);
assert.equal(root.dataset.transition, 'open');
transition.hide(true);
assert.equal(root.hidden, true);
transition.show(false);
f.reduce(); await f.flush();
assert.equal(root.dataset.transition, 'open');
f.media.matches = false;
transition.hide(false, () => closed++);
transition.dispose(); await f.advance(300);
assert.equal(closed, 3, 'disposed completion must not run');
assert.equal(f.active.size, 0);
assert.equal(f.listeners.size, 0);
transition.show(false); transition.finish(); await f.flush();
assert.equal(root.dataset.transition, 'open');
transition.dispose();
console.log('PASS surface: static copy, interruption, show/hide, hidden no-op, reduced/live reduction, dispose, finish');
