import assert from 'node:assert/strict';
import { fixture, loadMotion } from './motion-fixture.mjs';
const { wipeNavigate, defaultWipeTiming: t } = await loadMotion('lib/ui-transitions.ts');
for (const theme of ['paper', 'ink']) {
  const f = fixture(theme);
  wipeNavigate('#play', { note: 'test', title: 'Fixed text' });
  const layer = f.body.children[0], [plate, copy] = layer.children;
  assert.equal(layer['aria-hidden'], 'true');
  assert.equal(plate.children.length, 0, 'moving plane must contain no text');
  assert.equal(copy.children[1].textContent, 'Fixed text');
  assert.equal(copy.hidden, true);
  assert.ok(f.all.every(a => a.node === plate));
  wipeNavigate('#wrong', { note: '', title: '' });
  assert.equal(f.body.children.length, 1, 'prevent competing navigation');
  await f.advance(t.cover - 1);
  assert.equal(window.location.hash, '');
  await f.advance(1);
  assert.equal(window.location.hash, '#play', 'navigate only at opaque coverage');
  assert.equal(copy.hidden, false);
  await f.advance(t.hold);
  assert.equal(copy.hidden, true, 'copy disappears before material departure');
  await f.advance(t.exit);
  assert.equal(f.body.children.length, 0);
  assert.equal(f.active.size, 0);
  assert.equal(f.listeners.size, 0);
  console.log('PASS ' + theme + ': coverage, static copy, reentry, exit and cleanup');
  wipeNavigate('#reduced-midway', { note: '', title: '' });
  f.reduce(); await f.flush();
  assert.equal(window.location.hash, '#reduced-midway');
  assert.equal(f.body.children.length, 0);
  await f.advance(5000);
  assert.equal(f.body.children.length, 0, 'cancelled hold cannot reappear');
  wipeNavigate('#instant', { note: '', title: '' });
  assert.equal(window.location.hash, '#instant');
  assert.equal(f.body.children.length, 0);
  console.log('PASS ' + theme + ': initial and live reduced-motion, no stale callback');
}
